// codegen:start {preset: barrel, include: ./operations/*.ts, prefix: "@tsplus/stdlib/collections/HashSet"}
export * from "@tsplus/stdlib/collections/HashSet/operations/add"
export * from "@tsplus/stdlib/collections/HashSet/operations/beginMutation"
export * from "@tsplus/stdlib/collections/HashSet/operations/difference"
export * from "@tsplus/stdlib/collections/HashSet/operations/empty"
export * from "@tsplus/stdlib/collections/HashSet/operations/endMutation"
export * from "@tsplus/stdlib/collections/HashSet/operations/equals"
export * from "@tsplus/stdlib/collections/HashSet/operations/every"
export * from "@tsplus/stdlib/collections/HashSet/operations/filter"
export * from "@tsplus/stdlib/collections/HashSet/operations/flatMap"
export * from "@tsplus/stdlib/collections/HashSet/operations/forEach"
export * from "@tsplus/stdlib/collections/HashSet/operations/from"
export * from "@tsplus/stdlib/collections/HashSet/operations/has"
export * from "@tsplus/stdlib/collections/HashSet/operations/intersection"
export * from "@tsplus/stdlib/collections/HashSet/operations/isSubset"
export * from "@tsplus/stdlib/collections/HashSet/operations/make"
export * from "@tsplus/stdlib/collections/HashSet/operations/map"
export * from "@tsplus/stdlib/collections/HashSet/operations/mutate"
export * from "@tsplus/stdlib/collections/HashSet/operations/partition"
export * from "@tsplus/stdlib/collections/HashSet/operations/reduce"
export * from "@tsplus/stdlib/collections/HashSet/operations/remove"
export * from "@tsplus/stdlib/collections/HashSet/operations/size"
export * from "@tsplus/stdlib/collections/HashSet/operations/some"
export * from "@tsplus/stdlib/collections/HashSet/operations/toCollection"
export * from "@tsplus/stdlib/collections/HashSet/operations/toggle"
export * from "@tsplus/stdlib/collections/HashSet/operations/union"
export * from "@tsplus/stdlib/collections/HashSet/operations/values"
// codegen:end
