tasks:
  - init: yarn && yarn build && npm i @recordreplay/replay-node-cli --global && npm i @recordreplay/replay --global
github:
  prebuilds:
    addCheck: true
vscode:
  extensions:
    - dbaeumer.vscode-eslint
