export * as atomicNumber from "@tsplus/stdlib/data/AtomicNumber";
export * as atomicReference from "@tsplus/stdlib/data/AtomicReference";
export * as duration from "@tsplus/stdlib/data/Duration";
export * as either from "@tsplus/stdlib/data/Either";
export * as environment from "@tsplus/stdlib/data/Environment";
export * as function from "@tsplus/stdlib/data/Function";
export * as option from "@tsplus/stdlib/data/Option";
export * as predicate from "@tsplus/stdlib/data/Predicate";
export * as tuple from "@tsplus/stdlib/data/Tuple";
