export * as associative from "@tsplus/stdlib/prelude/Associative";
export * as associativeIdentity from "@tsplus/stdlib/prelude/AssociativeIdentity";
export * as closure from "@tsplus/stdlib/prelude/Closure";
export * as covariant from "@tsplus/stdlib/prelude/Covariant";
export * as equivalence from "@tsplus/stdlib/prelude/Equivalence";
export * as hkt from "@tsplus/stdlib/prelude/HKT";
export * as identity from "@tsplus/stdlib/prelude/Identity";
export * as ord from "@tsplus/stdlib/prelude/Ord";
export * as ordering from "@tsplus/stdlib/prelude/Ordering";
