export { equals, equals_, getHash, getHash_, has, has_ } from "@tsplus/stdlib/collections/HashMap/_internal/hashMap"

// codegen:start {preset: barrel, include: ./HashMap/*.ts, prefix: "@tsplus/stdlib/collections"}
export * from "@tsplus/stdlib/collections/HashMap/asCollection"
export * from "@tsplus/stdlib/collections/HashMap/beginMutation"
export * from "@tsplus/stdlib/collections/HashMap/collect"
export * from "@tsplus/stdlib/collections/HashMap/collectWithIndex"
export * from "@tsplus/stdlib/collections/HashMap/compact"
export * from "@tsplus/stdlib/collections/HashMap/definition"
export * from "@tsplus/stdlib/collections/HashMap/empty"
export * from "@tsplus/stdlib/collections/HashMap/endMutation"
export * from "@tsplus/stdlib/collections/HashMap/filter"
export * from "@tsplus/stdlib/collections/HashMap/filterWithIndex"
export * from "@tsplus/stdlib/collections/HashMap/flatMap"
export * from "@tsplus/stdlib/collections/HashMap/flatMapWithIndex"
export * from "@tsplus/stdlib/collections/HashMap/forEach"
export * from "@tsplus/stdlib/collections/HashMap/forEachWithIndex"
export * from "@tsplus/stdlib/collections/HashMap/fromEntries"
export * from "@tsplus/stdlib/collections/HashMap/get"
export * from "@tsplus/stdlib/collections/HashMap/hasHash"
export * from "@tsplus/stdlib/collections/HashMap/isEmpty"
export * from "@tsplus/stdlib/collections/HashMap/keys"
export * from "@tsplus/stdlib/collections/HashMap/keySet"
export * from "@tsplus/stdlib/collections/HashMap/map"
export * from "@tsplus/stdlib/collections/HashMap/mapWithIndex"
export * from "@tsplus/stdlib/collections/HashMap/modify"
export * from "@tsplus/stdlib/collections/HashMap/modifyHash"
export * from "@tsplus/stdlib/collections/HashMap/mutate"
export * from "@tsplus/stdlib/collections/HashMap/node"
export * from "@tsplus/stdlib/collections/HashMap/reduce"
export * from "@tsplus/stdlib/collections/HashMap/reduceWithIndex"
export * from "@tsplus/stdlib/collections/HashMap/remove"
export * from "@tsplus/stdlib/collections/HashMap/removeMany"
export * from "@tsplus/stdlib/collections/HashMap/set"
export * from "@tsplus/stdlib/collections/HashMap/setTree"
export * from "@tsplus/stdlib/collections/HashMap/size"
export * from "@tsplus/stdlib/collections/HashMap/union"
export * from "@tsplus/stdlib/collections/HashMap/unsafeGet"
export * from "@tsplus/stdlib/collections/HashMap/update"
export * from "@tsplus/stdlib/collections/HashMap/values"
// codegen:end
