export * as doublyLinkedList from "@tsplus/stdlib/collections/mutable/DoublyLinkedList"
export * as listBuffer from "@tsplus/stdlib/collections/mutable/ListBuffer"
export * as mutableHashMap from "@tsplus/stdlib/collections/mutable/MutableHashMap"
export * as mutableHashSet from "@tsplus/stdlib/collections/mutable/MutableHashSet"
export * as mutableQueue from "@tsplus/stdlib/collections/mutable/MutableQueue"
