// codegen:start {preset: barrel, include: ./Equivalence/*.ts, prefix: "@tsplus/stdlib/prelude"}
export * from "@tsplus/stdlib/prelude/Equivalence/any"
export * from "@tsplus/stdlib/prelude/Equivalence/array"
export * from "@tsplus/stdlib/prelude/Equivalence/boolean"
export * from "@tsplus/stdlib/prelude/Equivalence/contramap"
export * from "@tsplus/stdlib/prelude/Equivalence/date"
export * from "@tsplus/stdlib/prelude/Equivalence/definition"
export * from "@tsplus/stdlib/prelude/Equivalence/never"
export * from "@tsplus/stdlib/prelude/Equivalence/number"
export * from "@tsplus/stdlib/prelude/Equivalence/orElseEither"
export * from "@tsplus/stdlib/prelude/Equivalence/strict"
export * from "@tsplus/stdlib/prelude/Equivalence/string"
export * from "@tsplus/stdlib/prelude/Equivalence/struct"
export * from "@tsplus/stdlib/prelude/Equivalence/symbol"
export * from "@tsplus/stdlib/prelude/Equivalence/tuple"
export * from "@tsplus/stdlib/prelude/Equivalence/zip"
// codegen:end
