export * as associative from "./prelude/Associative.js"
export * as closure from "./prelude/Closure.js"
export * as equivalence from "./prelude/Equivalence.js"
export * as identity from "./prelude/Identity.js"
export * as ord from "./prelude/Ord.js"
export * as ordering from "./prelude/Ordering.js"
