export * as associative from "@tsplus/stdlib/prelude/Associative"
export * as closure from "@tsplus/stdlib/prelude/Closure"
export * as equivalence from "@tsplus/stdlib/prelude/Equivalence"
export * as identity from "@tsplus/stdlib/prelude/Identity"
export * as ord from "@tsplus/stdlib/prelude/Ord"
export * as ordering from "@tsplus/stdlib/prelude/Ordering"
